version: 1.0
workflows:
  - subclass: WDL
    primaryDescriptorPath: /scenicplus.wdl
    name: scenicplus-wdl
    authors:
      - name: Deepika Yeramosu
        email: dyeramos@broadinstitute.org
  - subclass: WDL
    primaryDescriptorPath: /pycistopic.wdl
    name: pycistopic-wdl
    authors:
     - name: Deepika Yeramosu
       email: dyeramos@broadinstitute.org
  - subclass: WDL
    primaryDescriptorPath: /pycistarget.wdl
    name: pycistarget-wdl
    authors:
      - name: Deepika Yeramosu
        email: dyeramos@broadinstitute.org