version: 1.2

workflows:
  - name: scenicplus-wdl
    subclass: WDL
    primaryDescriptorPath: /scenicplus.wdl
    authors:
      - name: Deepika Yeramosu
        email: dyeramos@broadinstitute.org
  - name: pycistopic-wdl
    subclass: WDL
    primaryDescriptorPath: /pycistopic.wdl
    authors:
     - name: Deepika Yeramosu
       email: dyeramos@broadinstitute.org
  - name: pycistarget-wdl
    subclass: WDL
    primaryDescriptorPath: /pycistarget.wdl
    authors:
      - name: Deepika Yeramosu
        email: dyeramos@broadinstitute.org
  - name: geneactivityscores-wdl
    subclass: WDL
    primaryDescriptorPath: /geneactivityscores.wdl
    authors:
      - name: Deepika Yeramosu
        email: dyeramos@broadinstitute.org
  - name: downstream_scenic_analysis-wdl
    subclass: WDL
    primaryDescriptorPath: /downstream_scenic_analysis.wdl
    authors:
      - name: Deepika Yeramosu
        email: dyeramos@broadinstitute.org
  